# Dockerfile

# Use the official WordPress image as base
FROM wordpress:latest

# Set environment variables
ENV WORDPRESS_DB_HOST=db1:3306
ENV WORDPRESS_DB_NAME=wordpress_db1
ENV WORDPRESS_DB_USER=wordpress_user
ENV WORDPRESS_DB_PASSWORD=your_db_password