version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "8081:80"

  app2:
    build:
      context: ./app2
    container_name: app2
    ports:
      - "8082:80"