# Second WordPress service
FROM wordpress:latest

# Set environment variables
ENV WORDPRESS_DB_HOST=db2:3306
ENV WORDPRESS_DB_NAME=wordpress_db2
ENV WORDPRESS_DB_USER=wordpress_user
ENV WORDPRESS_DB_PASSWORD=your_db_password